### ISSUE TITLE
[FEATURE] Improving code standards

### ISSUE THREAD

**Issue by kvedala** [TheAlgorithms/C-Plus-Plus#880]
## Detailed Description

Now that the repo is somewhat normalized, has a compile and build tool, I tried to check the quality of the code therein. [![Language grade: C/C++](https://img.shields.io/lgtm/grade/cpp/g/TheAlgorithms/C-Plus-Plus.svg?logo=lgtm&logoWidth=18)](https://lgtm.com/projects/g/TheAlgorithms/C-Plus-Plus/context:cpp) 
and sadly found that the code standard is "E" which is quite poor. The report also lists out exactly why and what parts of the code are making it so. 

How about we have some volunteers use this opportunity to help improved the code with one file at a time. 
This will be great exercise for the learners who can read the code, understand it, learn it and actually contribute by improving it to the standards. A contribution doesn't always have to be a new code but many a times, it is an improvement on the existing ones. Like Einstein once said, he was but standing on the shoulders of giants.

**Comment by kvedala** [comment]
LGTM Analaysis configuration
```yml
extraction:
  cpp:
    prepare:
      packages:
      - "cmake"
      - "ninja-build"
    configure:
      command: "cmake -B build -S . -G Ninja"
    index:
      build_command: "cmake --build build -j 4"
```
